# GitHub Actions definition for CI build.

name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  WinBuildTest:
    name: Windows build and test
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        # No "with: dotnet-version" specified -> use global.json
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - name: Install ProjFS feature and run tests
        run: |
          Set-StrictMode -Version latest
          $ErrorActionPreference = "Stop"

          enable-WindowsOptionalFeature -online -featurename client-projfs
          dotnet test --no-build --configuration Release
        shell: powershell
